### ISSUE TITLE
비회원 Home 화면 UI 구현

### ISSUE THREAD

**Issue by jungseokyoung-cloud** [alloon-project/photi-ios#129]
## 💡 요약

비회원 Home 화면 UI 구현입니다.

## 💻 Todo

- [x] 비회원 Home화면 UI 구현
- [x] Login Flow 작업 완료 
- [x] 앱 Entry Point 수정 및 아키텍쳐 수정 
- [x] Image Stencil 작성
