### ISSUE TITLE
Home화면 챌린지 있을 때 UI 구현 

### ISSUE THREAD

**Issue by jungseokyoung-cloud** [alloon-project/photi-ios#132]
## 💡 요약

Home화면 챌린지 있을 때 UI 구현입니다.

## 💻 Todo

- [ ] 카메라 촬영 기능 구현
- [ ] 인증 CollecrionView 구현
- [ ] 내 Challenge UI 구현 완료
