### ISSUE TITLE
NavigationBar 리팩토링

### ISSUE THREAD

**Issue by jungseokyoung-cloud** [alloon-project/photi-ios#152]
## 💡 요약

NavigationBar 리팩토링입니다.

## 💻 Todo

- [x] NavigationBar 리팩토링
- [x] 기존 NavigationBar에서 커스텀 용이하게 수정
- [x] NavigationBar three모드일 때, 설정
- [x] Navigation type마다 분리
