### ISSUE TITLE
챌린지 개별 조회(회원) 버튼 클릭시 액션 및 UI 구현

### ISSUE THREAD

**Issue by jungseokyoung-cloud** [alloon-project/photi-ios#176]
## 💡 요약

챌린지 개별 조회(회원) 클릭시 UI 구현입니다.

## 💻 Todo

- [ ] 카메라 버튼 클릭시 액션 구현
- [ ] 최신순, 인기순 버튼  액션 구현
- [ ] feed 눌렀을 때, 댓글 상세보기 구현
