### ISSUE TITLE
회원가입(이메일, 이메일 인증 UI) 작업

### ISSUE THREAD

**Issue by jungseokyoung-cloud** [alloon-project/photi-ios#69]
## 💡 요약

회원가입 UI 작업입니다.

## 💻 Todo

- [x] 이메일 UI
- [x] 이메일 인증 UI
- [x] 다음 버튼 활성화 로직 
- [x] 경고 문구 관련 로직 
- [x] Login과 연결
