### ISSUE TITLE
회원가입 아이디 입력 UI 구현

### ISSUE THREAD

**Issue by jungseokyoung-cloud** [alloon-project/photi-ios#71]
## 💡 요약

회원가입 아이디 입력 UI 구현입니다.

## 💻 Todo

- [ ] 아이디 입력 UI 구현
- [ ] 버튼 활성화 로직
- [ ] 아이디 유효성 검사 로직
