### ISSUE TITLE
TabBar UI 작업 및 flow 연결

### ISSUE THREAD

**Issue by jungseokyoung-cloud** [alloon-project/photi-ios#92]
## 💡 요약

TabBar UI 작업 및 flow 연결입니다.

## 💻 Todo

- [x] TabBar UI 작업
- [x] TabBar에 Coordinator 연결
- [x] SignUp에서 플로우 작업
